# Generated by Django 3.0.5 on 2020-05-09 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=20, unique=True, verbose_name='项目名称')),
                ('project_type', models.CharField(blank=True, max_length=128, verbose_name='项目类型')),
                ('create_tiem', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用例项目表',
                'verbose_name_plural': '用例项目表',
                'db_table': 'case_project',
            },
        ),
        migrations.CreateModel(
            name='TestCases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(max_length=128, verbose_name='用例编号')),
                ('version_number', models.CharField(max_length=128, verbose_name='版本号')),
                ('module_name', models.CharField(blank=True, max_length=128, verbose_name='模块名称')),
                ('test_title', models.CharField(blank=True, max_length=128, verbose_name='测试标题')),
                ('condition', models.CharField(blank=True, max_length=128, verbose_name='前置条件')),
                ('step', models.CharField(max_length=128, verbose_name='测试步骤')),
                ('forecast_result', models.CharField(max_length=128, verbose_name='预期结果')),
                ('result', models.CharField(blank=True, max_length=128, verbose_name='实际结果')),
                ('test_person', models.CharField(blank=True, max_length=128, verbose_name='测试人员')),
                ('write_person', models.CharField(blank=True, max_length=128, verbose_name='用例编写人员')),
                ('remark', models.CharField(blank=True, max_length=128, verbose_name='备注')),
                ('create_tiem', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cases.CaseProject')),
            ],
            options={
                'verbose_name': '功能测试用例表',
                'verbose_name_plural': '功能测试用例表',
                'db_table': 'test_cases',
                'unique_together': {('case_id', 'version_number')},
            },
        ),
    ]
