# Generated by Django 3.0.5 on 2020-05-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CaseProject',
            new_name='ProjectCase',
        ),
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
        migrations.AlterModelTable(
            name='projectcase',
            table='project_case',
        ),
        migrations.AlterModelTable(
            name='testcase',
            table='test_case',
        ),
    ]
