# Generated by Django 3.0.5 on 2020-05-11 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_auto_20200509_0955'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcase',
            old_name='create_tiem',
            new_name='create_time',
        ),
        migrations.RenameField(
            model_name='testcase',
            old_name='create_tiem',
            new_name='create_time',
        ),
    ]
