# Generated by Django 3.0.5 on 2020-04-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200417_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-c_time'], 'verbose_name': '用户信息表', 'verbose_name_plural': '用户信息表'},
        ),
    ]
